plugins {
    id 'com.android.application'
}
android {
    namespace 'com.stellaros.voicechanger'
    compileSdk 34
    defaultConfig {
        applicationId "com.stellaros.voicechanger"
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName "2.0"
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
